### ISSUE TITLE
How do you work?

### ISSUE THREAD

**Issue by luismelodev** [JoeKarlsson/ama#2]
Hi Joe,

I see that you currently work at BestBuy as Sw. Engineer, do you work remotely? 
I am from Brazil, and just finished my Masters in Sw. Engineering (I hold a BSc in CS as well), but I seek for relocation in the industry!

**Comment by JoeKarlsson** [comment]
Hello @luishmelo! Thanks for stopping by! Yes, I do work remotely, but I now work for MongoDB. Best of luck relocating! Are you looking to come to the United States to be an Engineer?
